// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const computed: typeof import('vue')['computed']
  const defineComponent: typeof import('vue')['defineComponent']
  const get: typeof import('@vueuse/core')['get']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const set: typeof import('@vueuse/core')['set']
  const useNProgress: typeof import('@vueuse/integrations')['useNProgress']
  const useToast: typeof import('vue-toastification')['useToast']
  const watch: typeof import('vue')['watch']
}
export {}
