// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const addGuiFolder: typeof import('@depth/hud')['addGuiFolder']
  const and: typeof import('@vueuse/core')['and']
  const computed: typeof import('vue')['computed']
  const defineComponent: typeof import('vue')['defineComponent']
  const get: typeof import('@vueuse/core')['get']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const set: typeof import('@vueuse/core')['set']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const useNProgress: typeof import('@vueuse/integrations')['useNProgress']
  const useToast: typeof import('vue-toastification')['useToast']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
export {}
