// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AmbLight: typeof import('../components/preferences/GlobalAmbientLight.vue')['default']
    App: typeof import('./../App/App.vue')['default']
    Avatar: typeof import('./../3D/avatar.ts')['default']
    CancellableEventToast: typeof import('./../components/toasts/CancellableEventToast.vue')['default']
    CanvasInScene: typeof import('./../components/video/CanvasInScene.ts')['default']
    Debug: typeof import('./../components/ui/Debug.vue')['default']
    DirLight: typeof import('../components/preferences/GlobalDirectionalLight.vue')['default']
    Factories: typeof import('./../3D/factories.ts')['default']
    GlobalAmbientLight: typeof import('./../components/preferences/GlobalAmbientLight.vue')['default']
    GlobalDirectionalLight: typeof import('./../components/preferences/GlobalDirectionalLight.vue')['default']
    Help: typeof import('./../components/ui/Help.vue')['default']
    ImgMemfs: typeof import('./../components/ui/ImgMemfs.vue')['default']
    InfiniteGrid: typeof import('./../3D/infiniteGrid.ts')['default']
    ItemProgress: typeof import('./../components/ui/ItemProgress.vue')['default']
    LoadingScreen: typeof import('./../App/LoadingScreen.vue')['default']
    MainScene: typeof import('./../App/MainScene.vue')['default']
    SceneDefaults: typeof import('./../3D/sceneDefaults.ts')['default']
    StepProgressBar: typeof import('./../components/ui/StepProgressBar.vue')['default']
    StickmanLandmarks: typeof import('./../3D/characters/StickmanLandmarks.vue')['default']
    StickmanNormalized: typeof import('./../3D/characters/StickmanNormalized.vue')['default']
    StickmanSimple: typeof import('./../3D/characters/StickmanSimple.ts')['default']
    SystemCheck: typeof import('./../App/SystemCheck.ts')['default']
    'SystemCheck.spec': typeof import('./../App/SystemCheck.spec.ts')['default']
    ThreeCanvas: typeof import('./../App/ThreeCanvas.vue')['default']
    ThreeGlobe: typeof import('./../3D/ThreeGlobe.ts')['default']
    Title: typeof import('./../components/ui/Title.vue')['default']
    VideoPlayer: typeof import('./../components/video/VideoPlayer.vue')['default']
    VideoToPose: typeof import('./../components/video/VideoToPose.vue')['default']
    WebcamPlayer: typeof import('./../components/video/WebcamPlayer.vue')['default']
    WebcamToPose: typeof import('./../components/video/WebcamToPose.vue')['default']
  }
}

export { }
