// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Debug: typeof import('./../components/ui/Debug.vue')['default']
    DefaultLights: typeof import('./../components/3d/DefaultLights.ts')['default']
    FloatingText: typeof import('./../components/ui/FloatingText.vue')['default']
    FloorPlane: typeof import('./../3d/components/FloorPlane.vue')['default']
    GradientPyramid: typeof import('./../3d/components/GradientPyramid.vue')['default']
    ImagePlane: typeof import('./../components/3d/ImagePlane.ts')['default']
    InfiniteGrid: typeof import('./../components/3d/InfiniteGrid.ts')['default']
    LeafPlane: typeof import('./../components/3d/LeafPlane.ts')['default']
    MemoryInfo: typeof import('./../components/ui/MemoryInfo.vue')['default']
    SimpleBox: typeof import('./../3d/components/SimpleBox.vue')['default']
    SkyBox: typeof import('./../3d/components/SkyBox.ts')['default']
    ThreeGlobe: typeof import('./../components/3d/ThreeGlobe.ts')['default']
    Title: typeof import('./../components/ui/Title.vue')['default']
    VoxelWorld: typeof import('./../components/3d/VoxelWorld.ts')['default']
  }
}

export { }
