[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--prefix=/dev/null"

[build]
publish = "web/dist"
# command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
command = "npx pnpm i -r --shamefully-hoist --store=node_modules/.pnpm-store && npx pnpm run build"
# command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm run build"
