[router]
transition = true

[[router.routes]]
path = "video-pose"
position = [2, 1, -4]
lookAt = [2, 2, 0]

[[router.routes]]
path = "scene-setup"
position = [-2, 2, -10]
lookAt = [0, 0, 0]

[[router.routes]]
path = "empty"
label = "Empty"
component = "EmptyTemplate"
position = [-30, 2, -10]
lookAt = [30, 2, -20]

[sounds]
volume = 0.45

[sounds.samples]
denied = "/sounds/249300__suntemple__access-denied.wav"
