[router]
transition = true
damping = 0.069

[[router.routes]]
path = ""
label = "Home"
component = "Home"
position = [0, 0, 0]
lookAt = [6, 9, 6]

[[router.routes]]
path = "video-pose"
position = [0, 1.6, 0]
lookAt = [0, 1.6, -10]

[[router.routes]]
path = "db-admin"
label = "Database Admin"
position = [0, 1.6, 0]
lookAt = [0, 1.6, 10]

[[router.routes]]
path = "scene-setup"
position = [-2, 2, -10]
lookAt = [0, 0, 0]

[[router.routes]]
path = "empty"
label = "Empty"
component = "EmptyTemplate"
position = [-30, 2, -30]
lookAt = [-300, 2, -30]

[audio]
volume = 0.45

[audio.samples]
denied = "sounds/249300__suntemple__access-denied.wav"

[video]
clips = [
  "videos/yoga2.webm",
  "videos/extended_leg_pistol_squats.webm"
]
