import type { Landmark, NormalizedLandmark } from "../../public/pose";
export declare function kebabToTitle(str: string): string;
export declare function arrayToObject<T>(arr: T[], key: string): Record<string, T>;
export declare function flipHorizontal(keypoint: NormalizedLandmark): NormalizedLandmark;
export declare function normaliseKeypointToDisplay(point: Landmark, scale: number, zMulti: number): [number, number, number];
export declare function formatToTimeline(secs: number): string;
export declare function basename(src: string, ext?: boolean): string;
export declare function capitalize(str: string): string;
export declare function scaleKeypoint(width: number, height: number, scale: number, zMulti: number, keypoint: THREE.Vector3, flipX?: boolean, flipY?: boolean): THREE.Vector3Tuple;
export declare function toSelectOptions(urls: string[]): {};
export declare function normalizeDeviceLabel(label: string): string;
