// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('C:/Users/subzt/Code/depth/src/components/scene/App.vue')['default']
    CancellableEventToast: typeof import('C:/Users/subzt/Code/depth/src/components/toasts/CancellableEventToast.vue')['default']
    CanvasInScene: typeof import('C:/Users/subzt/Code/depth/src/components/video/CanvasInScene.ts')['default']
    DbAdmin: typeof import('C:/Users/subzt/Code/depth/src/components/pages/DbAdmin.vue')['default']
    Debug: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Debug.vue')['default']
    EmptyTemplate: typeof import('C:/Users/subzt/Code/depth/src/components/pages/EmptyTemplate.vue')['default']
    Help: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Help.vue')['default']
    ImgMemfs: typeof import('C:/Users/subzt/Code/depth/src/components/video/ImgMemfs.vue')['default']
    MainScene: typeof import('C:/Users/subzt/Code/depth/src/components/scene/MainScene.vue')['default']
    SceneSetup: typeof import('C:/Users/subzt/Code/depth/src/components/pages/SceneSetup.vue')['default']
    StepProgressBar: typeof import('C:/Users/subzt/Code/depth/src/components/ui/StepProgressBar.vue')['default']
    StickmanLandmarks: typeof import('C:/Users/subzt/Code/depth/src/components/characters/StickmanLandmarks.vue')['default']
    StickmanNormalized: typeof import('C:/Users/subzt/Code/depth/src/components/characters/StickmanNormalized.vue')['default']
    StickmanSimple: typeof import('C:/Users/subzt/Code/depth/src/components/characters/StickmanSimple.ts')['default']
    StoreTest: typeof import('C:/Users/subzt/Code/depth/src/components/pages/StoreTest.vue')['default']
    SystemCheck: typeof import('C:/Users/subzt/Code/depth/src/components/scene/SystemCheck.ts')['default']
    ThreeCanvas: typeof import('C:/Users/subzt/Code/depth/src/components/scene/ThreeCanvas.vue')['default']
    TimelineCanvas: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelineCanvas.vue')['default']
    TimelineCursor: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelineCursor.vue')['default']
    TimelinePlayhead: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelinePlayhead.vue')['default']
    Title: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Title.vue')['default']
    VideoPlayer: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoPlayer.vue')['default']
    VideoPose: typeof import('C:/Users/subzt/Code/depth/src/components/pages/VideoPose.vue')['default']
    VideoTimeline: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoTimeline.vue')['default']
  }
}

export { }
