// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('../App/App.vue')['default']
    Avatar: typeof import('C:/Users/subzt/Code/depth/src/3D/avatar.ts')['default']
    Camerashake: typeof import('C:/Users/subzt/Code/depth/src/3D/camerashake.ts')['default']
    CancellableEventToast: typeof import('C:/Users/subzt/Code/depth/src/components/toasts/CancellableEventToast.vue')['default']
    CanvasInScene: typeof import('C:/Users/subzt/Code/depth/src/components/video/CanvasInScene.ts')['default']
    DbAdmin: typeof import('C:/Users/subzt/Code/depth/src/components/pages/DbAdmin.vue')['default']
    Debug: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Debug.vue')['default']
    EmptyTemplate: typeof import('C:/Users/subzt/Code/depth/src/components/pages/EmptyTemplate.vue')['default']
    Factories: typeof import('C:/Users/subzt/Code/depth/src/3D/factories.ts')['default']
    Help: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Help.vue')['default']
    Home: typeof import('C:/Users/subzt/Code/depth/src/components/pages/Home.vue')['default']
    ImgMemfs: typeof import('C:/Users/subzt/Code/depth/src/components/video/ImgMemfs.vue')['default']
    InfiniteGrid: typeof import('C:/Users/subzt/Code/depth/src/3D/infiniteGrid.ts')['default']
    MainScene: typeof import('../App/MainScene.vue')['default']
    SceneDefaults: typeof import('C:/Users/subzt/Code/depth/src/3D/sceneDefaults.ts')['default']
    SceneSetup: typeof import('C:/Users/subzt/Code/depth/src/components/pages/SceneSetup.vue')['default']
    SelectVideoClip: typeof import('C:/Users/subzt/Code/depth/src/components/video/SelectVideoClip.ts')['default']
    StatefulVideoPlayer: typeof import('C:/Users/subzt/Code/depth/src/components/video/StatefulVideoPlayer.vue')['default']
    StepProgressBar: typeof import('C:/Users/subzt/Code/depth/src/components/ui/StepProgressBar.vue')['default']
    StickmanLandmarks: typeof import('C:/Users/subzt/Code/depth/src/3D/characters/StickmanLandmarks.vue')['default']
    StickmanNormalized: typeof import('C:/Users/subzt/Code/depth/src/3D/characters/StickmanNormalized.vue')['default']
    StickmanSimple: typeof import('C:/Users/subzt/Code/depth/src/3D/characters/StickmanSimple.ts')['default']
    StoreTest: typeof import('C:/Users/subzt/Code/depth/src/components/pages/StoreTest.vue')['default']
    SystemCheck: typeof import('C:/Users/subzt/Code/depth/src/components/scene/SystemCheck.ts')['default']
    ThreeCanvas: typeof import('../App/ThreeCanvas.vue')['default']
    ThreeGlobe: typeof import('C:/Users/subzt/Code/depth/src/3D/ThreeGlobe.ts')['default']
    TimelineCanvas: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelineCanvas.vue')['default']
    TimelineCursor: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelineCursor.vue')['default']
    TimelinePlayhead: typeof import('C:/Users/subzt/Code/depth/src/components/video/TimelinePlayhead.vue')['default']
    Title: typeof import('C:/Users/subzt/Code/depth/src/components/ui/Title.vue')['default']
    VideoClipPlayer: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoClipPlayer.vue')['default']
    VideoKeyframes: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoKeyframes.ts')['default']
    VideoKeyTimes: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoKeyTimes.ts')['default']
    VideoPlayer: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoPlayer.vue')['default']
    VideoPose: typeof import('C:/Users/subzt/Code/depth/src/components/pages/VideoPose.vue')['default']
    VideoPoses: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoPoses.ts')['default']
    VideoStorePlayer: typeof import('C:/Users/subzt/Code/depth/src/components/stateful/VideoStorePlayer.ts')['default']
    VideoTimeline: typeof import('C:/Users/subzt/Code/depth/src/components/video/VideoTimeline.vue')['default']
    WebcamPlayer: typeof import('C:/Users/subzt/Code/depth/src/components/video/WebcamPlayer.vue')['default']
  }
}

export { }
